### PR TITLE
Always destroy the socket

### PR DESCRIPTION
**Pull request by xPaw**
This fixes socket throwing connection errors.

### CODE REVIEW

**Comment by astorije** [comment]
@prawnsalad, any chance of reviewing/merging this sometime?
https://github.com/thelounge/lounge/issues/352 could use this :-)

**Comment by YaManicKill** [comment]
Another ping, @prawnsalad 

Would be good to get this in as we are nearly finished on thelounge 2.0.0, and this is one of the few blockers.

**Comment by MaxLeiter** [comment]
From IRC:

> prawnsalad: ive not hit any issues myself with irc-framework in testing yet, but this week it will be slowly rolling out to a few thousand connections so itl be a good test then
> im not 100% that the PR is the root cause for the issue your seeing which is why its not merged, but if there is something wrong this will show it up

**Comment by xPaw** [comment]
I don't remember the exact details anymore, but I believe that *was* the cause.

**Comment by astorije** [comment]
@xPaw, did you close this because that was fixed upstream?

**Comment by prawnsalad** [comment]
@astorije, this was fixed in https://github.com/kiwiirc/irc-framework/commit/28c035e0cde629be6ad4eddd935b4fb6240c40dc

**Comment by astorije** [comment]
Awesome @prawnsalad!
@xPaw, does that mean that https://github.com/thelounge/lounge/issues/352 will be fixed next time we bump `irc-framework`? 🎉

**Pull request closed without merging**
