### PR TITLE
Remove read_buffer and parse irc line straight away

### PR DESCRIPTION
**Pull request by xPaw**
This appears to be left overs from old kiwi when connecting + transport was not split into different components.

javascript is synchronous, so `read_buffer` will never have more than 1 entry, making all of this processing pretty useless.

I actually tried logging `processed_lines` when connecting to ZNC (it sends a lot of data, so `line` is emitted a lot), it's never over 1.

### CODE REVIEW

**Comment by prawnsalad** [comment]
The idea behind this is that if you get a large mass of lines then it introduces some js ticks between processing them giving some time for other things to be processed. More noticeable on the browser and frame rendering. https://github.com/kiwiirc/irc-framework/pull/197/files#diff-875da84119066ec244742e95d1209f0cL288

Depending on the app using the lib and the number of messages being received, the buffer may or may not reach above 1 message in normal cases.

**Comment by xPaw** [comment]
Well at least on node `read_buffer` never goes over 1 because it all happens synchronously. I don't imagine websocket implementation in the browser being any different here.

**Comment by xPaw** [comment]
Looking at websocket transport, it uses `eventemitter3` which is also synchronous. Which means the entire `processReadBuffer` is also synchronous and thus logically `processed_lines` can never have more than one entry in it.

**Comment by xPaw** [comment]
@prawnsalad Mind taking another look at this, as per the reply above?

**Comment by prawnsalad** [comment]
@xPaw I will hopefully be able to get to this one this week. I need to test the performance in the browser before + after to see if it's still relevant.

**Comment by xPaw** [comment]
Can you give this a look? 🙈

**Comment by xPaw** [comment]
Rebased on master.

To give a simple explanation on why this is redundant.
```
            that.read_buffer.push(line);
            that.processReadBuffer();
```

`processReadBuffer` is always executed after pushing to `read_buffer` and logically there will never be more than one entry in that array.

**Comment by prawnsalad** [comment]
https://github.com/kiwiirc/irc-framework/pull/197/files#diff-875da84119066ec244742e95d1209f0cL290

This is the part that requires the read_buffer. During large amounts of incoming data such as `/list` output, it can get stuck in `processReadBuffer` processing every line it has without giving the application or browser time to do anything else, essentially locking it up. So I give it a short breather after `lines_per_js_tick` before it continues processing the read buffer again.

**Comment by xPaw** [comment]
From IRC:
```
12:19 <xPaw> prawnsalad, read_buffer will never be higher than 1 
12:19 <xPaw> so that settimeout is never called
12:20 <xPaw> either i'm completely blind, or there is logically no way for the buffer to have more than 1 line in the array before process is called
12:22 <xPaw> looking at old kiwi code, it was possible there because it put the parsed socked data into buffer, and then called parse
12:23 <xPaw> but irc-framework emits a line event, which puts it into buffer and calls process, so its always called after each line
12:26 <xPaw> i just put a log there before setTimeout, connected to znc and did /list on freenode, it just never gets called
```

If you want buffering behaviour, then transports need to be changed not to emit one `line` event that comes from the network.

**Comment by prawnsalad** [comment]
Re-looking over this now step by step I see what you're saying now - not sure why I didn't see that at the time. Apologies for the back forth here.

If we can keep the `addReadBuffer()` function to prevent backward compat issues that would be good. It's used in kiwi for injecting raw s>c traffic for example.

**Comment by xPaw** [comment]
Changed it to keep the function, but didn't give it a test.

**Pull request merged**
