### PR TITLE
Replace runes

### PR DESCRIPTION
**Pull request by vith**

### CODE REVIEW

**Comment by prawnsalad** [comment]
From what I can see, this can now throw errors. Shouldn't we be wrapping this call with a try/catch now then?

**Comment by xPaw** [comment]
Yeah exceptions will be a breaking change, and I'm not entirely sure how useful they are in the context where this function is used.

Catching them might not be ideal as it will end up not sending the message to the server. Perhaps a simpler approach here would be keeping the old behaviour? (just force the split, or keep the long string and send it as-is).

**Comment by prawnsalad** [comment]
Forcing the split is probably the only thing we can do here

**Comment by vith** [comment]
I don't see what we'd do with a try/catch around it in irc-framework. Whatever's calling the irc-framework methods could potentially retain the text in the input field ui when a `GraphemeTooLargeForLineError` is thrown, and display an error message to the user to allow them to edit the grapheme cluster that makes their message unsendable.

We can use the `{ allowBreakingGraphemes: true }` option to get closer to the previous behavior if that's preferred. Then the only exception that could be thrown is `CodepointTooLargeForLineError`, which would only happen with insane server configs. i.e. where you have less than 4 bytes available for the whole message.

The previous implementation didn't throw in that situation because it was measuring in units of codepoints instead of bytes.

**Comment by xPaw** [comment]
> hich would only happen with insane server configs. i.e. where you have less than 4 bytes available for the whole message.

That's not entirely true because you can construct some insane unicode stuff that won't even fit in 500 bytes, e.g. see ios crash bugs related to text handling.

**Comment by vith** [comment]
> That's not entirely true because you can construct some insane unicode stuff that won't even fit in 500 bytes, e.g. see ios crash bugs related to text handling.

Yes, but with `{ allowBreakingGraphemes: true }` it would just break those things up. The largest codepoint size is 4 bytes. The limitless potential of grapheme cluster size is why `GraphemeTooLargeForLineError` exists.

**Comment by xPaw** [comment]
Then that should be set by default.

What exactly is being achieved here by providing these options? I miss some context for that, if you're writing a finely tuned version specifically for user input splitting.

**Comment by vith** [comment]
The options are there because:

- I was originally going to make this an external library
- They provide a way to adjust the correctness-vs-convenience tradeoff, if not everyone can agree on what behavior is desired (I don't like the idea of breaking graphemes)
- They make it easier to compare the difference between allowing and disallowing certain types of line breaking in tests like https://github.com/kiwiirc/irc-framework/pull/208/files#diff-7b862a8a4e28e44433a7517a99d0c5bdR109

**Comment by xPaw** [comment]
So now the behaviour is the same as currently on master, the only difference being it will try to split on spaces between words?

https://github.com/kiwiirc/irc-framework/blob/55ca1189512b53aafb270af3ad5a1b940f2a7810/test/stringToChunks.js#L69-L75

This test shows me that this space that is being split is lost, it's a minor thing, but if the space would be preserved at the beginning of second and further lines, it could prevent unintentional bot command triggers. This is just a suggestion/observation, what do you think about this edge case?

**Comment by vith** [comment]
> So now the behaviour is the same as currently on master, the only difference being it will try to split on spaces between words?

It will try to split at word boundaries first, fall back to splitting at grapheme boundaries if a word can't fit in a line, and then fall back to splitting at codepoints if a grapheme can't fit in a line.

> This test shows me that this space that is being split is lost, it's a minor thing, but if the space would be preserved at the beginning of second and further lines, it could prevent unintentional bot command triggers. This is just a suggestion/observation, what do you think about this edge case?

I think we will just leave it as-is for now. In *the future* when there are line continuation tags or batch types in play, bots will have the opportunity to parse the split messages with proper semantics.

**Pull request merged**
