### PR TITLE
Fix nick assignment in RPL_WHOISEND

### PR DESCRIPTION
**Pull request by xPaw**
Bug introduced in 8ed019e0e2012d7f714b5ca4d2898d524b3944d8

### CODE REVIEW

**Comment by prawnsalad** [comment]
Good catch, thanks!

**Comment by astorije** [comment]
Hey @prawnsalad, any chance this could make it into a patch release? :)

**Comment by prawnsalad** [comment]
Depending on some other changes I'm currently making, there will either be a patch or minor release made later today.

**Comment by astorije** [comment]
Hey @prawnsalad, did you drop the ball on this? :D

**Pull request merged**
