### PR TITLE
fix 'this' shadowing in IrcChannel causing errors

### PR DESCRIPTION
**Pull request by vith**

### CODE REVIEW

**Comment by vith** [comment]
https://github.com/kiwiirc/irc-framework/blob/68981ab9abc5116532bdc61f3a5e4ab296786b2f/src/channel.js#L88

`this` is a reference to the anonymous function it's inside, which has no `users` property:

https://github.com/kiwiirc/irc-framework/blob/68981ab9abc5116532bdc61f3a5e4ab296786b2f/src/channel.js#L77

It was meant to access

https://github.com/kiwiirc/irc-framework/blob/68981ab9abc5116532bdc61f3a5e4ab296786b2f/src/channel.js#L24

which is a property of the class instance.

Replacing the anonymous function with an arrow function avoids creating a new `this`, so the intended property access can succeed.

**Comment by prawnsalad** [comment]
Could you add the semi colons back in place and I'll then get this merged

**Comment by vith** [comment]
I don't think you can have a semicolon there, since it's an expression and not a statement now (no curly braces, not a block/function body, implicit return).

**Comment by prawnsalad** [comment]
Ah my bad, the code wrapping made it look like a function block.

**Pull request merged**
