### PR TITLE
Ping timeout fix - #96

### PR DESCRIPTION
**Pull request by bews**
Tested, fixes problem #96.

### CODE REVIEW

**Comment by prawnsalad** [comment]
This is harshly killing the network connection even when safely connected. It should only call `.destroy()` when the network is a known bad state, eg. after a ping timeout.

You could add a `force` argument here https://github.com/bews/irc-framework/blob/aec4e27d9ddbc7fdfb627bf5b1d0dcc95d54dedb/src/transports/net.js#L191
And then change this https://github.com/bews/irc-framework/blob/aec4e27d9ddbc7fdfb627bf5b1d0dcc95d54dedb/src/transports/net.js#L193 to `if ((this.socket && this.state === SOCK_CONNECTING) || force) {`.

Then the final change for it to actually take effect, change https://github.com/bews/irc-framework/blob/aec4e27d9ddbc7fdfb627bf5b1d0dcc95d54dedb/src/connection.js#L226
to `this.transport.close(!!had_error);`.

This would play nicer with the IRC servers and network.

**Comment by bews** [comment]
I'll test that way too (just to be sure) and update PR later.

**Comment by MaxLeiter** [comment]
@bews any update?

**Comment by bews** [comment]
Yeah, tests were successful, I'll update PR tomorrow.

**Comment by bews** [comment]
Updated, thanks for the hints @prawnsalad!

**Pull request merged**
